### ISSUE TITLE
Systray - Unable to patch both 6.1 or git version of Dwm

### ISSUE THREAD

**Issue by ghost** [jceb/dwm-clean-patches#2]
**Edited:** 
Sorry, my bad...its working fine! haha

Thanks anyway! 

I could not patch Dwm 6.1 with any diff listed on dwm systray page:

Steps:

`wget https://dl.suckless.org/dwm/dwm-6.1.tar.gz
`

`cd dwm-6.1`

`wget https://raw.githubusercontent.com/jceb/dwm-clean-patches/master/6.1/1647_56a31dc4a7be459e3a1ea06d45427e1a4087a1a6/dwm-systray-20160731-56a31dc.diff`

`patch -p1 < dwm-systray-20160731-56a31dc.diff`

`4 out of 33 hunks FAILED -- saving rejects to file dwm.c.rej`

> 
> dwm.c.rej
> https://gist.github.com/oldgaro/ce368544f697809f73d9ac607a16e1d1

**_Git version:_**
`git clone git://git.suckless.org/dwm`

thanks!

**Comment by oldgaro** [comment]
Sorry my bad...its working fine! haha

**Comment by john2x** [comment]
Following the steps above, I'm getting the same issue as "ghost".
